### ISSUE TITLE
Migrate off BuildKite

### ISSUE THREAD

**Issue by benbz** [matrix-org/matrix-synapse-saml-mozilla#14]
We're ramping down our BuildKite usage and this project is one of the few left on it. How much work would it be to migrate to GH Actions/similar so that CI was under your span of control?

**Comment by DMRobertson** [comment]
I can't seem to see the project on https://buildkite.com/matrix-dot-org/matrix-synapse-saml-mozilla --- is it alive?

(I ask because the repo doesn't have any buildkit config in it. It probably just runs tox, which should be easy enough to port to GHA.)

**Comment by DMRobertson** [comment]
Ahhh, I forgot there was a pipelines repo! Thanks.

**Comment by DMRobertson** [comment]
Should be easy to convert---happy to commit to doing it before end of this calendar year.
