### ISSUE TITLE
SAML SSO for Mozilla via Github failing with bad /authn_response

### ISSUE THREAD

**Issue by jryans** [matrix-org/matrix-synapse-saml-mozilla#7]
Transferred from @ara4n's https://github.com/vector-im/riot-web/issues/12801:

> Hope this is the right place to say this: I tried to signup using github but after the authorization was done, redirected to mozilla.modular.im and the webpage was like:
>> Method Not Allowed Your browser approached me (at /_matrix/saml2/authn_response) with the method "GET". I only allow the method HEAD here.

Convo is here: https://matrix.to/#/!pcfWjiETvnVuspPLPl:mozilla.org/$IO71OeAO1JOD9WeTOiTZ5_uOJahvRyO840AoWfip9Dg?via=mozilla.org&via=matrix.org&via=maunium.net

**Comment by richvdh** [comment]
I believe this is fixed by https://github.com/matrix-org/synapse/pull/7058.

**Comment by babolivier** [comment]
> I believe this is fixed by [matrix-org/synapse#7058](https://github.com/matrix-org/synapse/pull/7058).

Yep, and it's been released (so should soon be deployed) therefore I'm closing this issue.
